#:schema ../override-schema.json

["22.S092"]
lectureUnits = 3
labUnits = 0
preparationUnits = 9
level = "U"
meets = "22.S902"
prereqs = "Physics I, Physics II"
description = "Explore the science and technology behind nuclear weapons.  Topics include: nuclear weapon effects, nuclear physics and supporting technologies, criticality,  yield, fusion ignition, technologies for the production of radioactive materials for nuclear weapons, doctrines governing nuclear weapons and relationship to design, environmental effects of weapons production, mitigation & cleanup of wastes; environmental effects of nuclear weapons production and nuclear war, arms control and verification, nuclear safeguards and forensics."
name = "Science and Technology of Nuclear Weapons"
inCharge = "Haruko Wainwright"
new = true

["22.S902"]
lectureUnits = 3
labUnits = 0
preparationUnits = 9
level = "G"
meets = "22.S092"
description = "Explore the science and technology behind nuclear weapons.  Topics include: nuclear weapon effects, nuclear physics and supporting technologies, criticality,  yield, fusion ignition, technologies for the production of radioactive materials for nuclear weapons, doctrines governing nuclear weapons and relationship to design, environmental effects of weapons production, mitigation & cleanup of wastes; environmental effects of nuclear weapons production and nuclear war, arms control and verification, nuclear safeguards and forensics."
name = "Science and Technology of Nuclear Weapons"
inCharge = "Haruko Wainwright"
new = true

["22.S906"]
lectureUnits = 3
labUnits = 0
preparationUnits = 9
level = "G"
prereqs = "Permission of instructor"
description = "This graduate seminar course will consider the re-emergence of the nuclear energy sector as a focus of invention and new technology applications in fission and fusion and will introduce concepts, tools and perspectives important for nuclear innovators.   Basic concepts for analyzing the economic and financial aspects of long-lived, capital-intensive projects will be reviewed, and national differences in market and supply chain structures and government policies will be considered.  Topics will include safety and environmental regulation; nuclear security and dual-use technology regulation; new/non-traditional markets for nuclear energy services; and public and private roles in nuclear innovation and operations.   The course is intended for students in Nuclear Science and Engineering but may also be useful for students with broader or adjacent interests in innovation management and policy."
name = "Topics in Nuclear Innovation"
inCharge = "Richard Lester"
new = true

["22.S908"]
lectureUnits = 2
labUnits = 0
preparationUnits = 4
level = "G"
description = "Advanced characterization of fuels and structural materials; covers X-ray scattering, diffraction, imaging and spectroscopy for nuclear materials; setting up in situ/operando experiments relevant to nuclear energy systems."
name = "Advanced Nuclear Materials Characterization: Theory and Practice"
inCharge = "Ericmoore Jossou"
new = true
