#:schema ../override-schema.json

["ES.S10"]
name = "Many Interesting Things (MIT)"
inCharge = "Christian Cardozo"
description = "Computation and communication: they shape our world as we know it today. But these technologies didn’t emerge from thin air—they were born from common human experience, logic, and physics. From basic Python to artificial intelligence, from building a computer to connecting millions of them across the globe: we’ll introduce these topics in an accessible way for everyone, regardless of background. By term’s end, we’ll have explored many of the interesting classes of MIT, but without the pressure of actually being in them—learning for learning’s sake. No prereqs, no psets, no pressure!"

["ES.S11"]
name = "Trieste Project"

["ES.S50"]
name = "Composing the Cosmos: Music, Science, and Cultural Heritage"
inCharge = "Brian Urra"
description = "Whether you have musical experience, or are new to music, learn about fundamental ideas and concepts that you can apply to compose music that relates to your scientific interests and cultural heritage! We will start from a six-movement orchestral suite (composed by the instructor) that explores black holes while engaging with the cultural and natural landscapes of the Atacama Desert and the traditions of Música Andina. Over the course of the semester you will create your own multidisciplinary project, synthesizing original music composition, visual media, and science. We will celebrate the end of the semester with a class concert, during which the students’ projects will be played by professional musicians."

["ES.S70"]
name = "Hack Yourself: Data-Driven Wellbeing and Learning"
same = "6.S056"
meets = "6.S056"
description = "Do you want to take charge of your wellbeing and learn at your best? In this seminar, you will discover how with practices based on positive psychology supported by data. At the end of the semester, you will have a toolkit of over 60 new habits plus some experience with data science tools you can use to “hack” yourself. Pre-req 6.100A or equivalent knowledge. Limited to 12, priority to ESG students."

["ES.S71"]
name = "Transformers and Neural Networks"
inCharge = "Alexis Montecinos"
description = "This 6-week seminar offers an introduction to Artificial Intelligence (AI) and its real-world applications through neural networks, image recognition, time series forecasting, and natural language processing (NLP). Designed for students with basic Python skills, the seminar combines conceptual learning with hands-on coding to help participants understand how machines can learn from data to make predictions, recognize patterns, and interpret human language. This seminar provides a comprehensive overview of advanced AI techniques using Python. Students will learn to implement deep neural networks across medicine, business, finance, and other scientific and technological domains."

["ES.7016"]
name = "Introductory Biology"
number = "ES.7016"
description = "Equivalent to 7.016; see 7.016 for description. Instruction provided through small, interactive classes. Limited to students in ESG."
course = "ES"
subject = "7016"
sectionKinds = ["lecture"]
lectureRawSections = [
    "TBD/MTWRF/0/9",
    "TBD/MTWRF/0/10",
    "TBD/MWRF/0/2;TBD/T/0/1",
]
lectureSections = [
    [
        [
            [
                6,
                2,
            ],
            [
                40,
                2,
            ],
            [
                74,
                2,
            ],
            [
                108,
                2,
            ],
            [
                142,
                2,
            ],
        ],
        "TBD",
    ],
    [
        [
            [
                8,
                2,
            ],
            [
                42,
                2,
            ],
            [
                76,
                2,
            ],
            [
                110,
                2,
            ],
            [
                144,
                2,
            ],
        ],
        "TBD",
    ],
    [
        [
            [
                16,
                2,
            ],
            [
                50,
                2,
            ],
            [
                84,
                2,
            ],
            [
                116,
                2,
            ],
            [
                152,
                2,
            ],
        ],
        "TBD",
    ],
]
lectureUnits = 5
preparationUnits = 7
labUnits = 0
level = "U"
terms = ["SP"]
prereqs = "None"
tba = false
hass = []
comms = ""
gir = "BIOL"
isVariableUnits = false
same = ""
meets = ""
virtualStatus = false
inCharge = "P. Christie"
nonext = false
repeat = false
url = "https://esg.mit.edu/learn-at-esg/subject-offerings/"
final = false
half = false
limited = true
rating = 0
hours = 0
size = 0
new = true
include = true
