#:schema ../override-schema.json

["21L.600"]
lectureUnits = 2
labUnits = 2
preparationUnits = 8
lectureRawSections = ["2-103/MTWR/0/9.30-12"]
lectureSections = [[[[7, 5], [41, 5], [75, 5], [109, 5]], "2-103"]]
