name: CI checks for the backend

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.{ts,tsx,js,md,txt,toml}"
      - "{.vscode,deploy/cron_scripts,public}/**/*"
      - ".editorconfig"
      - ".gitignore"
      - "{package,package-lock,tsconfig}.json"
      - "scrapers/overrides.toml.d/override-schema.json"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.{ts,tsx,js,md,txt,toml}"
      - "{.vscode,deploy/cron_scripts,public}/**/*"
      - ".editorconfig"
      - ".gitignore"
      - "{package,package-lock,tsconfig}.json"
      - "scrapers/overrides.toml.d/override-schema.json"

env:
  python-version: 3.7

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable
  pylint:
    name: Pylint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
  integration:
    name: Test for valid JSON output
    runs-on: ubuntu-22.04 #NOTE: python 3.7 is NOT supported on ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Run scrapers
        run: python3 -m scrapers
      - name: Check existence of public/latest.json
        run: test -f public/latest.json || exit 1
